#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
- name: Add necessary roles for 'cmadminrole' 
  freeipa.ansible_freeipa.iparole:
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: cmadminrole
    privilege:
      - Group Administrators
      - User Administrators
      - Host Enrollment
      - Host Administrators
      - Host Group Administrators
      - Modify Group membership
      - Modify Users and Reset passwords
      - Service Administrators
      - Sudo Administrator
      - Stage User Administrators
      - Delegation Administrator
    action: member

# Set cmadmin-XXXX user in FreeIPA as an admin

- name: Get cmadmin exact name from ipa cli
  shell: | 
      echo "{{ ipa_admin_password }}" | kinit admin 
      ipa user_find cmadmin | grep "User login" | cut -d : -f 2 | xargs
  register: ipa_cmadmin_answer

- name: Get exact cmadmin_name from iap cli answer
  set_fact:
    cmadmin_name: "{{ ipa_cmadmin_answer.stdout.split('\n')[1] }}"

- name: DEBUG - cmadmin_name
  debug:
    msg: "{{ cmadmin_name }}"
  when: debug | default(false)

- name: Add cmadmin to admins group
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: admins 
    user:
      - "{{ cmadmin_name }}"
    action: member

- name: Add cmadmin to trust admins group
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: trust admins 
    user:
      - "{{ cmadmin_name }}"
    action: member